<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Blog
 */
?>
<?php $categories = $block->getCategories(); ?>
<?php if (count($categories)) : ?>
    <div class="amblog-category">
        <?= $block->escapeHtml(__('Posted in: ')); ?>
        <?php $isFirst = true; ?>
        <?php foreach ($categories as $category) : ?>
            <?= (!$isFirst) ? ',' : ''; ?>
            <a class="amblog-ref"
               href="<?= $block->escapeUrl($category->getUrl()); ?>"
                title="<?= $block->escapeHtml($category->getName()); ?>">
                <?= $block->escapeHtml($category->getName()); ?>
            </a>
            <?php $isFirst = false; ?>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
