<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile


?>
<table class="data-table admin__table-secondary order-subtotal-table">
    <?php $_totals = $block->getTotals('footer')?>

    <?php if ($_totals):?>
        <tfoot>
            <?php foreach ($block->getTotals('footer') as $_code => $_total): ?>
                <?php if ($_total->getBlockName()): ?>
                    <?= $block->getChildHtml($_total->getBlockName(), false) ?>
                <?php else:?>
                <tr class="col-<?= /* @escapeNotVerified */ $_code ?>">
                    <td <?= /* @escapeNotVerified */ $block->getLabelProperties() ?> class="label">
                        <strong><?= $block->escapeHtml($_total->getLabel()) ?></strong>
                    </td>
                    <td <?= /* @escapeNotVerified */ $block->getValueProperties() ?>>
                        <strong><?= /* @escapeNotVerified */ $block->formatValue($_total) ?></strong>
                    </td>
                </tr>
                <?php endif?>
            <?php endforeach?>
        </tfoot>
    <?php endif?>

    <?php $_totals = $block->getTotals('');
    $_code = 0;?>
    <?php if ($_totals):?>
        <tbody>
            <?php foreach ($_totals as $_code => $_total): ?>
                <?php if ($_total->getBlockName()): ?>
                    <?= $block->getChildHtml($_total->getBlockName(), false) ?>
                <?php else:?>
                    <tr class="col-<?= /* @escapeNotVerified */ $_code ?>">
                        <td <?= /* @escapeNotVerified */ $block->getLabelProperties() ?> class="label">
                            <?php if ($_total->getStrong()):?>
                            <strong><?= $block->escapeHtml($_total->getLabel()) ?></strong>
                            <?php else:?>
                            <?= $block->escapeHtml($_total->getLabel()) ?>
                            <?php endif?>
                        </td>

                        <?php if ($_total->getStrong()):?>
                            <td <?= /* @escapeNotVerified */ $block->getValueProperties() ?>>
                                <strong><?= /* @escapeNotVerified */ $block->formatValue($_total) ?></strong>
                            </td>
                        <?php else:?>
                            <td <?= /* @escapeNotVerified */ $block->getValueProperties() ?>>
                                <span><?= /* @escapeNotVerified */ $block->formatValue($_total) ?></span>
                            </td>
                        <?php endif?>
                    </tr>
                <?php endif?>
            <?php endforeach?>
            <?php if($this->getSource()->getCoupondiscountTotal()){ ?>
        	<tr class="col-2">
                <td class="label">
                    <?php echo "GyFTR Voucher(".$this->getSource()->getCoupondiscountCode().")"; ?>
                </td>

              
                    <td>
                        <span><?php echo '-'.$this->helper('Magento\Framework\Pricing\Helper\Data')->currency(number_format($this->getSource()->getCoupondiscountTotal(),2),true,false);
;?></span>
                    </td>
            </tr>
        <?php } ?>
        </tbody>
    <?php endif?>
</table>
