<?php
/**
 * Mage SMS - SMS notification & SMS marketing
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the BSD 3-Clause License
 * It is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/BSD-3-Clause
 *
 * @category    TOPefekt
 * @package     TOPefekt_Magesms
 * @copyright   Copyright (c) 2012-2017 TOPefekt s.r.o. (http://www.mage-sms.com)
 * @license     http://opensource.org/licenses/BSD-3-Clause
 */
?><?php $user = $block->profile->user; ?><?php $url = 'pay.topefekt.com/pay.php?user='.$user->getUser().'&passwd='.$user->getPasswd().'&country='.$user->getCountry().'&vat='.$block->getVat(); ?><p><?php echo __(' In case methods for credit purchase are not displayed properly, please click here:'); ?><a href="http://<?php echo $url; ?>" target="_blank"><?php echo __('Purchase Credit'); ?></a></p><br /><iframe frameborder="no" style="margin:0px;padding:0px;width:100%;height:400px" src="https://<?php echo $url.'&parentUrl='.$block->getBaseUrl(); ?>"></iframe>