<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
?>

<?php

$label_string =  $_product->getResource()->getAttribute('product_label')->getFrontend()->getValue($_product);

if($label_string) {
    $label_string_array =  explode(", ",$label_string);

    echo '<div class="products-label-wrapper">';


    foreach ($label_string_array as $label) {

        $lowercase = strtolower($label);

        $className = str_replace(" ","-", $lowercase);

        echo '<div class="product-labels '.$className.'">
                                    
                                    <div class="label-name">'.$label.'</div>
                                
                                <div class="product-snipe-right" id="DIV_1">
                                    <div class="product-snipe-top" id="DIV_2"></div>
                                    <div class="product-snipe-bottom" id="DIV_3"></div>
                                </div>
                                
                                </div>';
    }

    echo '</div>';
}

?>