<div class="row main-products">
	<div class="col-sm-12 col-xs-12 content-main">
		<div class="custom-tabs text-center">
			<div class="tab-1">
				<a href="<?php echo $block->getBaseUrl(); ?>come-as-you-are.html">Come as you are </a>
			</div>
			<div class="tab-2">
				<a href="#">Products</a>
				<i class="arrow right"></i>
			</div>
		</div>

		<div class="main-middle col-sm-12 col-xs-12">

			<div class="banner-contents col-sm-12 col-xs-12">
				<div class="banner-img col-sm-12 col-xs-12">
					<a href="<?php echo $block->getBaseUrl(); ?>classic-melon-unisex-clog.html" class="m-link">
						<img src="<?php echo $block->getViewFileUrl('images/customPages/desktop/2019_CAYA_ProductPage10_03.png');?>" style="width:100%" class="custom_mob_hide">	
						<img src="<?php echo $block->getViewFileUrl('images/customPages/mobile/2019_CAYA_ProductPage_03.png');?>" class="custom_desk_hide">	
						<div class="custom-product col-sm-offset-6 col-sm-6 col-xs-12">
								<img src="<?php echo $block->getViewFileUrl('images/customPages/desktop/2019_CAYA_ProductPage11_03.png');?>">	
								<div class="product-name">Classic Clog</div>
						</div>
					</a>
				</div>
			</div>

			<div class="middle-container col-sm-12 col-xs-12">
				<ul class="product-slider col-sm-12 col-xs-12 owl-carousel owl-theme" id="product-slider">
					<li class="item pro col-sm-3 col-xs-12">
						<a href="<?php echo $block->getBaseUrl(); ?>classic-melon-kids-unisex-clog.html" 
						class="text-center">
							<img src="<?php echo $block->getViewFileUrl('images/customPages/desktop/2019_CAYA_ProductPage_03.png');?>">
							<div class="product-name">Classic Clog</div>
						</a>
					</li>
					<li class="item pro col-sm-3 col-xs-12">
						<a href="<?php echo $block->getBaseUrl(); ?>crocband-graphic-iii-dark-camo-green-espresso-unisex-clog.html" class="text-center">
							<img src="<?php echo $block->getViewFileUrl('images/customPages/desktop/2019_CAYA_ProductPage_04.png');?>">
							<div class="product-name">Classic Clog</div>
						</a>
					</li>
					<li class="item pro col-sm-3 col-xs-12">
						<a href="<?php echo $block->getBaseUrl(); ?>classic-light-grey-unisex-clog.html" 
						class="text-center">
							<img src="<?php echo $block->getViewFileUrl('images/customPages/desktop/2019_CAYA_ProductPage_055.png');?>">
							<div class="product-name">Classic Clog</div>
						</a>
					</li>
					<li class="item pro col-sm-3 col-xs-12">
						<a href="<?php echo $block->getBaseUrl(); ?>classic-pool-kids-unisex-clog.html" class="text-center">
							<img src="<?php echo $block->getViewFileUrl('images/customPages/desktop/2019_CAYA_ProductPage_06.png');?>">
							<div class="product-name">Classic Clog</div>
						</a>
					</li>
				</ul>

				<div class="head-title col-sm-12 col-xs-12 text-center">
					<h4 class="custom-title">
						<a href="<?php echo $block->getBaseUrl(); ?>shop-classics.html">Shop Classic Collection</a>
					</h4>
				</div>

				<div class="block-one fpo col-sm-12 col-xs-12">
					<div class="col-sm-5 col-sm-offset-1 left col-xs-12">
						<h4>See How Zooey Gets Her Crocs On</h4>
						<img src="<?php echo $block->getViewFileUrl('images/customPages/desktop/2019_CAYA_ProductPage_03_new.png');?>" class="text-right custom_mob_hide">
						<img src="<?php echo $block->getViewFileUrl('images/customPages/mobile/2019_CAYA_ProductPage_12.png');?>" class="custom_desk_hide">
					</div>
					<div class="col-sm-6 right col-xs-12">
						<img src="<?php echo $block->getViewFileUrl('images/customPages/desktop/2019_CAYA_ProductPage2_03.png');?>" class="custom_mob_hide">
						<img src="<?php echo $block->getViewFileUrl('images/customPages/mobile/2019_CAYA_ProductPage_06.png');?>" class="custom_desk_hide">
					</div>
				</div>

				<ul class="product-slider second col-sm-12 col-xs-12 owl-carousel owl-theme" id="product-slider2">
					<li class="item pro col-sm-3 col-xs-12">
						<a href="<?php echo $block->getBaseUrl(); ?>crocband-light-grey-bright-coral-unisex-clog.html" 
						class="text-center">
							<img src="<?php echo $block->getViewFileUrl('images/customPages/desktop/2019_CAYA_ProductPage3_03.png');?>">
							<div class="product-name">Crocband <sup>TM</sup> Clog</div>
						</a>
					</li>
					<li class="item pro col-sm-3 col-xs-12">
						<a href="<?php echo $block->getBaseUrl(); ?>crocband-platform-barely-pink-pepper-unisex-clog.html" class="text-center">
							<img src="<?php echo $block->getViewFileUrl('images/customPages/desktop/2019_CAYA_ProductPage3_05.png');?>">
							<div class="product-name">Crocband <sup>TM</sup> Platform Clog</div>
						</a>
					</li>
					<li class="item pro col-sm-3 col-xs-12">
						<a href="<?php echo $block->getBaseUrl(); ?>catalogsearch/result/index/?p=2&q=crocband+slide" class="text-center">
							<img src="<?php echo $block->getViewFileUrl('images/customPages/desktop/2019_CAYA_ProductPage3_07.png');?>">
							<div class="product-name">Crocband <sup>TM</sup> Slide</div>
						</a>
					</li>
					<li class="item pro col-sm-3 col-xs-12">
						<a href="<?php echo $block->getBaseUrl(); ?>crocband-k-volt-green-lemon-kids-unisex-clog-1.html" class="text-center">
							<img src="<?php echo $block->getViewFileUrl('images/customPages/desktop/2019_CAYA_ProductPage3_09.png');?>">
							<div class="product-name">Crocband <sup>TM</sup> Clog</div>
						</a>
					</li>
				</ul>

				<div class="head-title second col-sm-12 text-center col-xs-12">
					<h4 class="custom-title">
						<a href="<?php echo $block->getBaseUrl(); ?>crocs-crocband-collection.html"><span>Shop Crocband</span> &nbsp; Collection</a> <sup>TM</sup>
					</h4>
				</div>

				<div class="block-two col-sm-12 col-xs-12">
					<div class="col-sm-5 col-sm-offset-1 left col-xs-12">
						<h4 class="custom_desk_hide">See Natalie Rock Some Serious Sandals</h4>
						<img src="<?php echo $block->getViewFileUrl('images/customPages/desktop/2019_CAYA_ProductPage4_03.png');?>" class="custom_mob_hide">
						<img src="<?php echo $block->getViewFileUrl('images/customPages/mobile/2019_CAYA_ProductPage_24.png');?>" class="custom_desk_hide">
					</div>
					<div class="col-sm-5 right col-xs-12">
						<h4 class="custom_mob_hide">See Natalie Rock Some Serious Sandals</h4>
						<img src="<?php echo $block->getViewFileUrl('images/customPages/desktop/2019_CAYA_ProductPage_11.png');?>" class="custom_mob_hide">
						<img src="<?php echo $block->getViewFileUrl('images/customPages/mobile/2019_CAYA_ProductPage_13.png');?>" class="custom_desk_hide">
					</div>
				</div>

				<ul class="product-slider three col-sm-12 col-xs-12 owl-carousel owl-theme" id="product-slider3">
					<li class="item pro col-sm-3 col-xs-12">
						<a href="<?php echo $block->getBaseUrl(); ?>serena-black-women-sandal.html" class="text-center">
							<img src="<?php echo $block->getViewFileUrl('images/customPages/desktop/2019_CAYA_ProductPage4_11.png');?>">
							<div class="product-name">Crocs Serena</div>
						</a>
					</li>
					<li class="item pro col-sm-3 col-xs-12">
						<a href="<?php echo $block->getBaseUrl(); ?>crocband-blue-flip-16.html" class="text-center">
							<img src="<?php echo $block->getViewFileUrl('images/customPages/desktop/2019_CAYA_ProductPage4_13.png');?>">
							<div class="product-name">Crocband <sup>TM</sup> Flip</div>
						</a>
					</li>
					<li class="item pro col-sm-3 col-xs-12">
						<a href="<?php echo $block->getBaseUrl(); ?>catalogsearch/result/index/?q=platform&style=268" class="text-center">
							<img src="<?php echo $block->getViewFileUrl('images/customPages/desktop/2019_CAYA_ProductPage4_14.png');?>">
							<div class="product-name">Crocband <sup>TM</sup> Platform Slide</div>
						</a>
					</li>
					<li class="item pro col-sm-3 col-xs-12">
						<a href="<?php echo $block->getBaseUrl(); ?>swiftwater-tropical-teal-light-grey-women-sandal.html" class="text-center">
							<img src="<?php echo $block->getViewFileUrl('images/customPages/desktop/2019_CAYA_ProductPage4_15.png');?>">
							<div class="product-name">Swiftwater <sup>TM</sup> Sandal</div>
						</a>
					</li>
				</ul>

				<div class="head-title col-sm-12 text-center col-xs-12">
					<h4 class="custom-title"><a href="#">Shop Sandals Collection</a></h4>
				</div>

			</div>

			<div class="banner-contents second col-sm-12 col-xs-12">
				<div class="banner-img col-sm-12 col-xs-12">
					<a href="<?php echo $block->getBaseUrl(); ?>literide-smoke-pearl-white-unisex-clog.html" class="m-link">
						<img src="<?php echo $block->getViewFileUrl('images/customPages/desktop/2019_CAYA_ProductPag_03.png');?>" style="width:100%" class="custom_mob_hide">
						<img src="<?php echo $block->getViewFileUrl('images/customPages/mobile/2019_CAYA_ProductPage_31.png');?>" class="custom_desk_hide">
						<div class="custom-product col-sm-offset-6 col-sm-6 col-xs-12">
								<img src="<?php echo $block->getViewFileUrl('images/customPages/desktop/2019_CAYA_ProductPa_03.png');?>">	
								<div class="product-name">LiteRide <sup>TM</sup> Clog</div>
						</div>
					</a>
				</div>
			</div>

			<div class="middle-container col-sm-12 col-xs-12">
				<ul class="product-slider four col-sm-12 col-xs-12 owl-carousel owl-theme" id="product-slider4">
					<li class="item pro col-sm-3 col-xs-12">
						<a href="<?php echo $block->getBaseUrl(); ?>literide-smoke-pearl-white-unisex-clog.html" class="text-center">
							<img src="<?php echo $block->getViewFileUrl('images/customPages/desktop/2019_CAYA_ProductPage5_05.png');?>">
							<div class="product-name">LiteRide <sup>TM</sup> Clog</div>
						</a>
					</li>
					<li class="item pro col-sm-3 col-xs-12">
						<a href="<?php echo $block->getBaseUrl(); ?>literide-melon-white-women-sandal.html" class="text-center">
							<img src="<?php echo $block->getViewFileUrl('images/customPages/desktop/2019_CAYA_ProductPage5_06.png');?>">
							<div class="product-name">Women's LiteRide <sup>TM</sup> Sandal</div>
						</a>
					</li>
					<li class="item pro col-sm-3 col-xs-12">
						<a href="<?php echo $block->getBaseUrl(); ?>literide-pacer-black-women-shoe.html" class="text-center">
							<img src="<?php echo $block->getViewFileUrl('images/customPages/desktop/2019_CAYA_ProductPage5_09.png');?>">
							<div class="product-name">LiteRide <sup>TM</sup> Pacer</div>
						</a>
					</li>
					<li class="item pro col-sm-3 col-xs-12">
						<a href="<?php echo $block->getBaseUrl(); ?>literide-mesh-slip-on-navy-white-men-shoe.html" class="text-center">
							<img src="<?php echo $block->getViewFileUrl('images/customPages/desktop/2019_CAYA_ProductPage5_11.png');?>">
							<div class="product-name">LiteRide <sup>TM</sup> Mesh Slip On</div>
						</a>
					</li>
				</ul>

				<div class="head-title second col-sm-12 text-center col-xs-12">
					<h4 class="custom-title">
						<a href="<?php echo $block->getBaseUrl(); ?>shop-literide-collection.html"><span>Shop LiteRide</span> &nbsp; Collection</a> <sup>TM</sup>
					</h4>
				</div>

			</div>

		</div>
	</div>
</div>

<div id="riskFreeFooterAsset" class="darkGrayText whiteBg bodyCopy">
	<div class="">
	<!-- dwMarker="content" dwContentID="668d872a4a6f2d8529497d2147" -->
	<div id="riskFreeContainer">
		<div class="cs_container">
			<div class="cs_row text-center">
				<div class="col-xs-12 text-gray-dark">
					<h2 class="bold">Risk Free Shopping</h2>
				</div>
				<div class="col-md-3">
					<a href="#">
						<img src="<?php echo $block->getViewFileUrl('images/customPages/170201_riskFree-icons-shipping.png');?>" alt="">
						<h3 id="lightboxfreeship" class="footer-header bold">Free Shipping</h3>
						<p>Valid on Economy Shipping method on all orders,for COD Rs.50 applicable</p>
					</a>
					<!--
					<p>Enjoy free shipping <br/>on qualifying orders.</p>
					-->
				</div>
				<div class="col-md-3">
					<a href="#">
						<img src="<?php echo $block->getViewFileUrl('images/customPages/170201_riskFree-icons-returns.png');?>" alt="">
						<h3 id="lightboxreturns" class="footer-header bold">Simple Returns</h3>
						<p>Change your mind? No problem. Our return process makes it easy.</p>
					</a>
				</div>
				<div class="col-md-3">
					<a href="#">
						<img width="52px" style="margin-top: 15px;" src="<?php echo $block->getViewFileUrl('images/customPages/170201_riskFree-icons-guarantee.png');?>" alt="">
						<h3 id="lightboxwarranty" class="footer-header bold">Crocs Guarantee</h3>
						<p>Crocs<sup style="top: 5px;">™</sup> products are covered by a 90-day warranty.</p>
					</a>
				</div>
				<div class="col-md-3 secure-info-container">
					<div id="siteseal" title="Click to Verify - This site chose Go Daddy SSL for secure e-commerce and confidential communications.">
						<script type="text/javascript" src="https://seal.godaddy.com/getSeal?sealID=PvNmDX1C1TR3Brz3GPe55XgTMY193g05vClMaZbeJMCh8V89jzVhiCd4wQ7l">
							
						</script>
						<img style="cursor:pointer;cursor:hand" src="https://seal.godaddy.com/images/3/en/siteseal_gd_3_h_l_m.gif" onclick="verifySeal();" alt="Godaddy Verified and Secured. Verify security." tabindex="0" role="link">
					</div>
					<h3 id="lightboxprivacy" class="footer-header">Your Information Is Secure</h3>
					<p>100% secured transaction using SSL encrypted connection.</p>
				</div>
			</div>
		</div>
	</div>

	<style class="x-keep">
	#riskFreeContainer {
		background: #ebebeb;
		width: 100%;
		padding: 10px 0 20px;
		overflow: hidden;
		font-size: 14px;
	}
	#riskFreeContainer img {
		display: block;
		margin: 0 auto 10px;
	}
	#riskFreeContainer a, #riskFreeContainer h2, #riskFreeContainer p, #riskFreeContainer .footer-header {
		font-weight: bold;
		letter-spacing: 0;
		margin-bottom: 5px;
		display: block;
	}
	#riskFreeContainer p {
		font-weight: normal;
		color: #444;
	}
	#riskFreeContainer .footer-header {
		font-size: 14px;
		line-height: 1.5;
		letter-spacing: auto;
	}
	#riskFreeContainer p sup {
		vertical-align: top;
	}
	#riskFreeContainer .secure-info-container img {
		margin: 23px auto 15px;
	}
	#riskFreeContainer h3{
		color: #444;
	}
	</style>

	<script>
		require(['jquery', 'jquery/ui'], function($){
		  	jQuery(document).ready( function() {
			// Make Godaddy siteseal code accessible
				var godaddySiteseal = {
					observer: null,
					el: $("#siteseal"),
					callback: function() {
						godaddySiteseal.el.find("img").attr({
							"alt": "Godaddy Verified and Secured. Verify security.",
							"tabindex": "0",
							"role": "link"
						}).on("keydown.godaddy", function(ev) {
							// triggers click event when enter or spacebar is pressed
							if (ev.which === 13 || ev.which === 32) {
								ev.preventDefault(); // prevent page scroll for spacebar
								$(this).click();
							}
						});
						// remove observer if it triggered the callback
						if (godaddySiteseal.observer) godaddySiteseal.observer.disconnect();
					}
				};

				if (godaddySiteseal.el.has("img")) {
					// siteseal img already loaded
					godaddySiteseal.callback();
				} else {
					// no img yet, add observer
					godaddySiteseal.observer = new MutationObserver(godaddySiteseal.callback);
					godaddySiteseal.observer.observe(godaddySiteseal.el[0], {childList: true});
				}
			});
		});
	</script>
	</div>
</div>

<script>
	require(['jquery', 'jquery/ui', "mageplaza/core/owl.carousel"], function($){
		jQuery(document).ready( function() {
			// var autoplayslider = autoplay === "true";
			var windowWidth = $(window).width();
    		if (windowWidth < 768) 
    		{	
    			$(".tab-2").click(function(){
				    $(".tab-1").fadeToggle();
				});
				$("#product-slider").owlCarousel({
					slideSpeed:200,
	                paginationSpeed: 800,
	                navigation : true,
	                dots: false,
	                margin:0,
	                responsiveClass:true,
	                navText: ["‹","›"],
	                responsive:{
	                    300: { items:1 },
	                    520: { items:1 },
	                    600: { items:2 },
	                    767: { items:3 },
	                    999: { items:3 },
	                    1280:{ items:3 }
	                }
	            });
	            $("#product-slider2").owlCarousel({
					slideSpeed:200,
	                paginationSpeed: 800,
	                navigation : true,
	                dots: false,
	                margin:0,
	                responsiveClass:true,
	                navText: ["‹","›"],
	                responsive:{
	                    300: { items:1 },
	                    520: { items:1 },
	                    600: { items:2 },
	                    767: { items:3 },
	                    999: { items:3 },
	                    1280:{ items:3 }
	                }
	            });
	            $("#product-slider3").owlCarousel({
					slideSpeed:200,
	                paginationSpeed: 800,
	                navigation : true,
	                dots: false,
	                margin:0,
	                responsiveClass:true,
	                navText: ["‹","›"],
	                responsive:{
	                    300: { items:1 },
	                    520: { items:1 },
	                    600: { items:2 },
	                    767: { items:3 },
	                    999: { items:3 },
	                    1280:{ items:3 }
	                }
	            });
	            $("#product-slider4").owlCarousel({
					slideSpeed:200,
	                paginationSpeed: 800,
	                navigation : true,
	                dots: false,
	                margin:0,
	                responsiveClass:true,
	                navText: ["‹","›"],
	                responsive:{
	                    300: { items:1 },
	                    520: { items:1 },
	                    600: { items:2 },
	                    767: { items:3 },
	                    999: { items:3 },
	                    1280:{ items:3 }
	                }
	            });
            }
            else
            {
            	$("ul").removeClass('owl-carousel owl-theme');
            }
		});
	});
</script>

<style type="text/css">
	.cms-products .page-wrapper .breadcrumbs
	{
	    display: none;
	}
	.cms-products .custom_mob_hide
	{
		display: block;
	}
	.cms-products .custom_desk_hide
	{
		display: none;
	}
	.cms-products #maincontent
	{
	    max-width: unset;
	}
	.cms-products .main-products
	{
	    padding-bottom: 100px;
	}
	.cms-products .main-products .content-main
	{
	    padding: 0px;
	}
	.cms-products .main-products .content-main .custom-tabs
	{
		background: #e4e4e4;
		padding: 10px;
		font-size: 1.5rem;
		text-transform: uppercase;
	}
	.cms-products .main-products .content-main .custom-tabs .tab-1,
	.cms-products .main-products .content-main .custom-tabs .tab-2
	{
	    display: inline-block;
	}
	.cms-products .main-products .content-main .custom-tabs .tab-1
	{
		margin-right: 60px;
	}
	.cms-products .main-products .content-main .custom-tabs .tab-2
	{
	    font-weight: 700;	
	}
	.cms-products .main-products .content-main .banner-contents
	{
		max-width: 1500px;
	    margin: 0 auto;
	}
	.cms-products .main-products .content-main .main-middle
	{
	    padding: 0px;
	}
	.cms-products .main-products .content-main .main-middle .banner-contents
	{
		float: unset;
		position: relative;
		padding: 0px;
	}
	.cms-products .main-products .content-main .main-middle .banner-contents .banner-img
	{
	    padding: 0px;	
	}
	.cms-products .main-products .content-main .main-middle .banner-contents .banner-img .m-link
	{
	    display: block;
	}
	.cms-products .main-products .content-main .main-middle .banner-contents .custom-product
	{
	    position: absolute;
	    top: 280px;
	    padding: 0px;
	}
	.cms-products .main-products .content-main .main-middle .banner-contents .custom-product .product-name
	{
		padding-left: 100px;
		font-size: 1.7rem;
	}
	.cms-products .main-products .content-main .main-middle .middle-container
	{
		padding: 0px;
	    margin: 0 auto;
	    max-width: 1500px;
	    float: unset;
	}
	.cms-products .main-products .content-main .main-middle .middle-container .product-slider
	{
	    padding: 0 70px;
        padding-top: 110px;
	}
	.cms-products .main-products .content-main .main-middle .middle-container .product-slider .pro
	{
		padding-left: 10px;
    	padding-right: 10px;
	}
	.cms-products .main-products .content-main .main-middle .middle-container .product-slider .pro a
	{
	    display: block;
	}
	.cms-products .main-products .content-main .main-middle .middle-container .product-slider .pro a img
	{
        height: 170px;	
	}
	.cms-products .main-products .content-main .main-middle .middle-container .product-slider .pro a 
	.product-name
	{
		font-size: 1.6rem;
	}
	.custom-title a 
	{
		text-decoration: underline;
		text-transform: uppercase;
	}
	.cms-products .main-products .content-main .main-middle .middle-container .head-title
	{
	    padding-top: 20px;
    	padding-bottom: 20px;
	}
	.cms-products .main-products .content-main .main-middle .middle-container .head-title .custom-title
	{
	    margin: 0px;
    	padding: 10px 0px 10px 0px;
	}
	.cms-products .main-products .content-main sup
	{
	    font-size: 0.7rem;
	    top: -1em;
	    left: -3px;
	}
	.cms-products .main-products .content-main .main-middle .middle-container .fpo
	{
		padding: 0px;
	    padding-top: 100px;
	}
	.cms-products .main-products .content-main .main-middle .middle-container .fpo .left
	{
	    padding-right: 5px;
    	text-align: right;
	    padding-top: 70px;
	}
	.cms-products .main-products .content-main .main-middle .middle-container .fpo .col-sm-offset-1 
	{
	    margin-left: 4.33333333%;
	}
	.cms-products .main-products .content-main .main-middle .middle-container .fpo .left
	h4
	{
	    width: 390px;
	    text-align: center;
	    float: right;
	    text-transform: uppercase;
	    font-weight: 700;
	    font-size: 20px;
	    padding-left: 70px;
	    padding-right: 70px;
	}
	.cms-products .main-products .content-main .main-middle .middle-container .fpo .left img
	{
		float: right;
	}
	.cms-products .main-products .content-main .main-middle .middle-container .fpo .right
	{
	    padding-left: 5px;
	}
	.cms-products .main-products .content-main .head-title.second sup
	{
	    left: -125px;
	}
	.cms-products .main-products .content-main .main-middle .middle-container .block-two
	{
	    padding: 0px;
        padding-top: 100px;
	}
	.cms-products .main-products .content-main .main-middle .middle-container .block-two .left
	{
	    padding-right: 5px;
    	margin-left: 10.33333333%;
	}
	.cms-products .main-products .content-main .main-middle .middle-container .block-two .left img
	{
	    float: right;
	}
	.cms-products .main-products .content-main .main-middle .middle-container .block-two .right
	{
	    padding-left: 5px;
        padding-top: 70px;
	}
	.cms-products .main-products .content-main .main-middle .middle-container .block-two .right h4
	{
		width: 390px;
	    text-align: center;
	    float: left;
	    text-transform: uppercase;
	    font-weight: 700;
	    font-size: 20px;
	    padding-left: 70px;
	    padding-right: 70px;
	}
	.cms-products .main-products .content-main .main-middle .banner-contents.second .banner-img
	{
	    padding-top: 100px;
	}
	.cms-products .main-products .content-main .main-middle .banner-contents.second .banner-img 
	.custom-product
	{
	    top: 380px;
	}
	#maincontent
	{
	    padding-bottom: 0px;
        padding-top: 0px;
	}
	#riskFreeFooterAsset
	{
		font-size: 12px;
		line-height: 15px;
		background: #ebebeb;
		padding-left: 30px;
		padding-right: 30px;
		margin-left: -15px;
		margin-right: -15px;
	}
	#riskFreeFooterAsset img:last-child
	{
		display: none;
	}
	@media screen and (max-width: 768px)
	{
		.cms-products .custom_mob_hide
		{
			display: none;
		}
		.cms-products .custom_desk_hide
		{
			display: block;
			width: 100%;
		}
		.cms-products .owl-nav
		{
			visibility: visible !important;
		    margin: 0;
		    position: absolute;
		    top: 50%;
		    left: 0;
		    width: 100%;
		    margin-top: -37px;
		    text-align: center;
		    -webkit-tap-highlight-color: transparent;
		}
		.cms-products .owl-nav .owl-prev
		{
		    position: absolute;
    		left: 5px;
    		display: block ! important;
		}
		.cms-products .owl-nav .owl-next
		{
		    position: absolute;
    		right: 5px;
    		display: block ! important;
		}
		.cms-products .product-slider
		{
			border-bottom: unset;
		}
		.cms-products .main-products .content-main .custom-tabs .tab-1
		{
		    display: none;
		}
		.cms-products .main-products .content-main .custom-tabs
		{
			padding-left: 0px;
    		padding-right: 0px;
		}
		.cms-products .main-products .content-main .custom-tabs .tab-1
		{
			margin: 0px;
			position: absolute;
			width: 100%;
			z-index: 1;
			left: 0px;
			padding: 10px 0px;
			background: #e4e4e4;
			top: 40px;
			border-top: 1px solid gray;
		}
		.cms-products .main-products .content-main .custom-tabs .tab-1 a
		{
		    width: 100%;
    		display: block;
		}
		.cms-products .main-products .content-main .custom-tabs .tab-2
		{
			display: block;
		}
		.cms-products .main-products .content-main .custom-tabs .tab-2 i 
		{
		  border: solid #3f3f3f;
		  border-width: 0 4px 4px 0;
		  display: inline-block;
		  padding: 6px;
		}
		.cms-products .main-products .content-main .custom-tabs .tab-2 i.right 
		{
			position: absolute;
			top: 9px;
			transform: rotate(45deg);
			-webkit-transform: rotate(45deg);
			right: 20px;
		}
		.cms-products .main-products .content-main .main-middle .banner-contents .banner-img .custom-product
		{
		    display: none;
		}
		.cms-products .main-products .content-main .main-middle .middle-container .block-one
		{
		    padding: 0px;
	        padding-top: 60px;
		}
		.cms-products .main-products .content-main .main-middle .middle-container .block-one .left
		{
		    margin: 0px;
    		padding: 0px;
		    padding-bottom: 50px;
		}
		.cms-products .main-products .content-main .main-middle .middle-container .block-one .left h4
		{
			width: 100%;
		    padding-left: 30px;
    		padding-right: 30px;
		}
		.cms-products .main-products .content-main .main-middle .middle-container .block-one .right
		{
			padding: 0px;
		}
		.cms-products .main-products .content-main .main-middle .middle-container .block-two
		{
			padding: 0px;
	        padding-top: 60px;
		}
		.cms-products .main-products .content-main .main-middle .middle-container .block-two .left 
		{
		    margin: 0px;
    		padding: 0px;
		}
		.cms-products .main-products .content-main .main-middle .middle-container .block-two .left 
		h4.custom_desk_hide
		{
	    	width: 100%;
    	    padding-left: 30px;
    		padding-right: 30px;
			text-align: center;
			float: right;
			text-transform: uppercase;
			font-weight: 700;
			font-size: 20px;
		}
		.cms-products .main-products .content-main .main-middle .middle-container .block-two .right
		{
		    padding-left: 0px;
    		padding-right: 0px;
		}
		.cms-products .main-products .content-main .main-middle .middle-container .product-slider
		{
			padding: 0px;
		}
		.cms-products .main-products .content-main .main-middle .middle-container .product-slider .pro
		{
		    padding-left: 40px;
    		padding-right: 40px;
		}
		.cms-products .main-products .content-main .main-middle .middle-container .product-slider .pro a img
		{
		    width: 100%;
    		height: auto;
		}
		.cms-products .main-products .content-main .main-middle .middle-container .product-slider.second,
		.cms-products .main-products .content-main .main-middle .middle-container .product-slider.three,
		.cms-products .main-products .content-main .main-middle .middle-container .product-slider.four
		{
		    padding-top: 40px;
		}
		.cms-products #riskFreeContainer p
		{
		    line-height: 1.5;
		}
		.cms-products #riskFreeContainer h2.bold
		{
	        font-size: 1.5rem;
		}
		.cms-products .page-header.type11 
		{
		    margin-bottom: 0px;
		}
	}
</style>