<div class="row main-come">
	<div class="come-as-section">
		<div class="custom-tabs text-center">
			<div class="tab-1">
				<a href="#">Come as you are</a>
				<i class="arrow right"></i>
			</div>
			<div class="tab-2" >
				<a href="<?php echo $block->getBaseUrl(); ?>products">Products</a>
			</div>
		</div>
		<div class="video-section">
			<iframe  src="https://player.vimeo.com/video/323919862?color=b8f0407149&title=0&byline=0&portrait=0&loop=true" class="videos">
			</iframe>
		</div>
		<div class="video-section-two">
			<iframe  src="https://player.vimeo.com/video/323920885?color=db247345e9&title=0&byline=0&portrait=0&loop=true" class="videos-two">
			</iframe>
		</div>
		<div class="section-content">
			<section class="content-meet">
				<h2 class="link-text">Meet The Crocs Stars</h2>
				<p class="cx-brand-font">Watch the new global cast of Come As You Are<sup>TM</sup> get comfortable in their own shoes!</p>
			</section>
		</div>
		<div class="slider-image-section">
			<ul class="list-slider owl-carousel owl-theme" id="banner-slide">
				<li class="part-list-one item">
					<div class="slider-one all-slider">
						<img src="<?php echo $block->getViewFileUrl('images/2019_CAYA_LandingPage_08.png'); ?>" class="slider-desk">
						<img src="<?php echo $block->getViewFileUrl('images/2019_CAYA_LandingPage_03_Copy.png'); ?>" class="slider-mob">
						<p class="slider-mob text">Zooey Deschanel </p>
						<p class="slider-mob text-two">Entertainer</p>
					</div>
					<div class="shoes-image">
						<a href="<?php echo $block->getBaseUrl(); ?>catalogsearch/result/?q=serena">
						<img src="<?php echo $block->getViewFileUrl('images/2019_CAYA_LandingPage_01_07.png'); ?>" class="sub-shoe-images">
						<p class="seerena-text">Crocs Serena</p>
						</a>
					</div>
					<div class="shoes-image-mob">
						<a href="<?php echo $block->getBaseUrl(); ?>catalogsearch/result/?q=serena">
						<img src="<?php echo $block->getViewFileUrl('images/2019_CAYA_LandingPage_01_11.png'); ?>" class="sub-shoe-mob">
						<p class="seerena-text">Crocs Serena</p>
						</a>
					</div>
				</li>
				<li class="part-list-one item">
					<div class="slider-two all-slider">
						<img src="<?php echo $block->getViewFileUrl('images/2019_CAYA_LandingPage_099.png'); ?>" class="slider-desk">
					</div>
					<div class="mob-im">
						<img src="<?php echo $block->getViewFileUrl('images/2019_CAYA_LandingPage_033.png'); ?>" class="slider-mob">
					</div>
				</li>
			</ul>
		</div>

		<div class="cs_row featured-categories-container text-center">
			<section class="sub-style">
				<h2 class="link-text-style"> The Hottest Styles of the year</h2> 
			</section>
			<div class="slider-section">
				<div class="shoe-one classic-slider col-sm-3 col-xs-6">
					<a href="<?php echo $block->getBaseUrl(); ?>shop-classics.html">
					<img src="<?php echo $block->getViewFileUrl('images/2019_CAYA_LandingPage_15.png'); ?>" class="classic-image">
					<p class="link-text-style">Classic Clog</p>
					</a>
				</div>
				<div class="shoe-two classic-slider col-sm-3 col-xs-6">
					<a href="<?php echo $block->getBaseUrl(); ?>crocs-swiftwater-collection.html?gender=81">
					<img src="<?php echo $block->getViewFileUrl('images/2019_CAYA_LandingPage_16.png'); ?>" class="classic-image swift">
					<p class="link-text-style">Women's Swiftwear<sup>TM</sup> Sandal</p>
					</a>
				</div>
				<div class="shoe-three classic-slider col-sm-3 col-xs-6">
					<a href="<?php echo $block->getBaseUrl(); ?>crocs-crocband-collection.html">
					<img src="<?php echo $block->getViewFileUrl('images/2019_CAYA_LandingPage_11.png'); ?>" class="classic-image crocband">
					<p class="link-text-style">Crocband<sup>TM</sup> Clog</p>
					</a>
				</div>
				<div class="shoe-four classic-slider col-sm-3 col-xs-6">
					<a href="<?php echo $block->getBaseUrl(); ?>newarrivals.html">
					<img src="<?php echo $block->getViewFileUrl('images/2019_CAYA_LandingPage_12.png'); ?>" class="classic-image crocs">
					<p class="link-text-style">Crocs Serena</p>
					</a>
				</div>
			</div>
			
	</div>
</div>
		<div class="bottom-section">
			<div class="explore-section">
				<a href="<?php echo $block->getBaseUrl(); ?>newarrivals.html" class="link-text-explore">
				<p class="ex-text">Explore Products</p></a>
			</div>
			<div class="all-image-section ">
				<div class="all image_one col-sm-3 col-xs-6">
					<img src="<?php echo $block->getViewFileUrl('images/2019_CAYA_LandingPage_25.png'); ?>" class="all-image-one">
				</div>
				<div class="all image_two col-sm-3 col-xs-6">
					<img src="<?php echo $block->getViewFileUrl('images/2019_CAYA_LandingPage_21.png'); ?>" class="all-image-two">
				</div>
				<div class="all image_three col-sm-3">
					<img src="<?php echo $block->getViewFileUrl('images/2019_CAYA_LandingPage_10.png'); ?>" class="all-image-three">
				</div>
				<div class="all image_four col-sm-3">
					<img src="<?php echo $block->getViewFileUrl('images/2019_CAYA_LandingPage_24.png'); ?>" class="all-image-four">
				</div>
			</div>
		</div>
	</div>
<div id="riskFreeFooterAsset" class="darkGrayText whiteBg bodyCopy">
	<div class="">
	<!-- dwMarker="content" dwContentID="668d872a4a6f2d8529497d2147" -->
	<div id="riskFreeContainer">
		<div class="cs_container">
			<div class="cs_row text-center">
				<div class="col-xs-12 text-gray-dark">
					<h2 class="bold">Risk Free Shopping</h2>
				</div>
				<div class="col-md-3">
					<a href="#">
						<img src="<?php echo $block->getViewFileUrl('images/customPages/170201_riskFree-icons-shipping.png');?>" alt="">
						<h3 id="lightboxfreeship" class="footer-header bold">Free Shipping</h3>
						<p class="footer-text">Valid on Economy Shipping method on all orders,for COD Rs.50 applicable.</p>
					</a>
					<!--
					<p>Enjoy free shipping <br/>on qualifying orders.</p>
					-->
				</div>
				<div class="col-md-3">
					<a href="#">
						<img src="<?php echo $block->getViewFileUrl('images/customPages/170201_riskFree-icons-returns.png');?>" alt="">
						<h3 id="lightboxreturns" class="footer-header bold">Simple Returns</h3>
						<p class="footer-text">Change your mind? No problem. Our return process makes it easy.</p>
					</a>
				</div>
				<div class="col-md-3">
					<a href="#">
						<img width="52px" style="margin-top: 15px;" src="<?php echo $block->getViewFileUrl('images/customPages/170201_riskFree-icons-guarantee.png');?>" alt="">
						<h3 id="lightboxwarranty" class="footer-header bold">Crocs Guarantee</h3>
						<p id="sec-text" class="footer-text">Crocs<sup style="top: 5px;">™</sup> products are covered by a 90-day warranty.</p>
					</a>
				</div>
				 <div class="col-md-3 secure-info-container">
                    <div id="siteseal" title="Click to Verify - This site chose Go Daddy SSL for secure e-commerce and confidential communications.">
                        <script type="text/javascript" src="https://seal.godaddy.com/getSeal?sealID=PvNmDX1C1TR3Brz3GPe55XgTMY193g05vClMaZbeJMCh8V89jzVhiCd4wQ7l">
                            
                        </script>
                        <img style="cursor:pointer;cursor:hand;display: none;" src="https://seal.godaddy.com/images/3/en/siteseal_gd_3_h_l_m.gif" onclick="verifySeal();" alt="Godaddy Verified and Secured. Verify security." tabindex="0" role="link">
                    </div>
                    <h3 id="lightboxprivacy" class="footer-header">Your Information Is Secure</h3>
                    <p class="footer-text">100% secured transaction using SSL encrypted connection.</p>
                </div>
			</div>
		</div>
	</div>
	<script>
	require(['jquery', 'jquery/ui', "mageplaza/core/owl.carousel"], function($){
		jQuery(document).ready( function() {
			// var autoplayslider = autoplay === "true";

			$("#banner-slide").owlCarousel({
				slideSpeed:200,
                paginationSpeed: 800,
                navigation : true,
                dots: false,
                margin:0,
                responsiveClass:true,
                navText: ["‹","›"],
                responsive:{
                    300: { items:1 },
                    520: { items:1 },
                    600: { items:1 },
                    767: { items:1 },
                    999: { items:1 },
                    1280:{ items:1 }
                }
            });

$(".tab-1").click(function(){
    $(".tab-2").fadeToggle();
})
		});
	});
	
</script>

	<style class="x-keep">
	#riskFreeFooterAsset
	{
		padding:0px;
	}
	#riskFreeContainer {
		background: #ebebeb;
		width: 100%;
		padding: 10px 0 20px;
		overflow: hidden;
		font-size: 14px;
	}
	#riskFreeContainer img {
		display: block;
		margin: 0 auto 10px;
	}
	#riskFreeContainer a, #riskFreeContainer h2, #riskFreeContainer p, #riskFreeContainer .footer-header {
		font-weight: bold;
		letter-spacing: 0;
		margin-bottom: 5px;
		display: block;
	}
	#riskFreeContainer p {
		font-weight: normal;
		color: #444;
	}
	#riskFreeContainer .footer-header {
		font-size: 14px;
		line-height: 1.5;
		letter-spacing: auto;
	}
	#riskFreeContainer p sup {
		vertical-align: top;
	}
	#riskFreeContainer .secure-info-container img {
		margin: 23px auto 15px;
	}
	#riskFreeContainer h3{
		color: #444;
	}
	
	</style>

	<script>
		// Make Godaddy siteseal code accessible
		var godaddySiteseal = {
			observer: null,
			el: $("#siteseal"),
			callback: function() {
				godaddySiteseal.el.find("img").attr({
					"alt": "Godaddy Verified and Secured. Verify security.",
					"tabindex": "0",
					"role": "link"
				}).on("keydown.godaddy", function(ev) {
					// triggers click event when enter or spacebar is pressed
					if (ev.which === 13 || ev.which === 32) {
						ev.preventDefault(); // prevent page scroll for spacebar
						$(this).click();
					}
				});
				// remove observer if it triggered the callback
				if (godaddySiteseal.observer) godaddySiteseal.observer.disconnect();
			}
		};

		if (godaddySiteseal.el.has("img")) {
			// siteseal img already loaded
			godaddySiteseal.callback();
		} else {
			// no img yet, add observer
			godaddySiteseal.observer = new MutationObserver(godaddySiteseal.callback);
			godaddySiteseal.observer.observe(godaddySiteseal.el[0], {childList: true});
		}
	</script>
	</div>
</div>

<style type="text/css">
.main-come
{
	padding-bottom: 100px;
}
#maincontent
{
	padding: 0px;
}
.videos-two, .shoes-image-mob
{
	display: none;
}
.custom-tabs
{
	background: #e4e4e4;
    padding: 10px;
    font-size: 1.5rem;
    text-transform: uppercase;\
    text-align: center;
}
.tab-1
{
    margin-right: 60px;
    display: inline-block;
    font-weight: 700;
}
.tab-2
{
	display: inline-block;
}
.breadcrumbs
{
	display: none;
}
.slider-mob
{
	display: none;
}
	.section-tab
	{
		background-color: lightgrey;
		text-align: center;
	}		
	.link-text
	{
		color: red;
	}
	.sub-slider
	{
		width: 30%;
	}	
	.slider-desk
	{
		width: 100%;
	}
	#maincontent
	{
		max-width: unset;
	    padding-left: 0px;
	    padding-right: 0px;
	}
	.videos
	{
		width: 100%;
    	height: calc(56.25vw);
	}
	#player
	{
		background-position: unset;
	}
	.section-content
	{
		padding: 5% 0px;
	}
	h2.link-text
	{
		text-align: center;
	    font-weight: 900;
	    font-size: 35px;
	    margin-bottom: 1%;
	}
	p.cx-brand-font
	{
		text-align: center;
	    font-size: 25px;
	    margin: 0px 30%;
	}
	.sub-style
	{
		padding-bottom: 2%;
    	padding-top: 4%;
	}
	h2.link-text-style
	{
		line-height: 45px;
	    font-size: 38px;
	    margin: 0px 34%;
	    font-family: inherit;
	    color: red;
	    font-weight: 900;
	    text-transform: uppercase;
	}
	p.link-text-style
	{
		font-size: 15px
	}
	div.slider-section
	{
		margin: 0px 15%;
	}
	div.cs_row.featured-categories-container.text-center
	{
		padding-bottom: 2%;
		padding-top: 0px;
	}
	div.all-slider
	{
		padding-left: 10%;
		padding-right: 10%;
		position: relative;
	}
	img.classic-image 
	{
		height: 160px;
	}
	.shoes-image
	{
		position: absolute;
	    left: 54%;
	    margin-top: -14%;
	}
	.sub-shoe-images
	{
		max-width: unset;
    	width: 100%;
	}
	p.seerena-text
	{
		margin-left: 20%;
		font-size: 15px;
	}
	.link-text
	{
		text-transform: uppercase;
   	    line-height: 34px;
	}
	p.ex-text
	{
		text-align: center;
	    font-size: 30px;
	    text-decoration: underline;
	    text-transform: uppercase;
	    padding-bottom: 10%;
	}
	div.all
	{
		padding: 0px;
	}
	.image_one
	{
		position: relative;
	    z-index: 1;
	    left: 1px;
    	top: 80px;
	}
	.all-image-one
	{
		width: 110%;
		max-width: unset;
	}
	.image_two
	{
		position: relative;
    	left: 0px;
	}
	.all-image-two
	{
		width: 100%;
	}
	.image_three
	{
		position: relative;
    	top: 140px;
	}
	img.all-image-three
	{
		width: 100%;
	}
	.image_four
	{
		position: relative;
    	top: 65px;
	}
	.mob-im
	{
		padding:0px 10%;
	}
	/*slider*/
	.owl-nav
	{
		position: relative;
	    left: 0;
	    top: 0;
	}
	.owl-prev
	{
		display: block ! important;
		position: absolute;
	    left: 3%;
	    bottom: 400px;
	    border: none ! important;
	}
	.owl-next
	{
		display: block ! important;
		position: absolute;
	    right: 3%;
	    bottom: 400px;
	    border: none ! important;
	}
	.come-as-section .slider-image-section ul.list-slider.owl-loaded.owl-drag .owl-stage-outer
	{
		position: relative;
    	overflow: hidden;
	}
	.come-as-section .slider-image-section ul.list-slider.owl-loaded.owl-drag .owl-stage
	{
		position: relative;
	}
	.come-as-section .slider-image-section ul.list-slider.owl-loaded.owl-drag .owl-stage .owl-item
	{
		position: relative;
    	float: left;
	}
	.owl-carousel .owl-item img.slider-mob
	{
		display: none;
	}
	.owl-carousel.owl-loaded
	{
		border-bottom: none;
	}
	.owl-carousel .owl-item
	{
		margin-bottom: 6%;
	}
	/*mobile*/
	@media screen and (max-width: 767px)
	{
		.video-section, .slider-desk, .shoes-image
		{
			display: none;
		}
		.videos-two
		{
			height: -webkit-fill-available;
			display: block;
			width: 100%;
		}
		.slider-mob
		{
			display: block;
			margin-left: 0px;
		    width: 100%;
		}
		
		h2.link-text
		{
			margin-right: 20%;
    		margin-left: 20%;
    		font-size: 24px;
		}
		.owl-prev, .owl-next
		{
			top: 150px;
		}
		.section-content
		{
			padding: 10% 10%;
		}
		p.cx-brand-font
		{
			font-size: 17px;
    		margin: 0px;
		}
		h2.link-text-style
		{
		    font-size: 25px;
		    line-height: 30px;
		    margin: 0px 13%;
		}
		p.link-text-style
		{
			font-size: 14px;
		}
		.sub-style
		{
			padding-bottom: 8%;
		}
		div.shoe-one, div.shoe-two, div.shoe-three, div.shoe-four
		{
			padding:0px;
		}
		img.classic-image
		{
			height: 100px;
		}
		.explore-section
		{
			display: none;
		}
		.image_one
		{
			position: relative;
		    z-index: 10;
		    top: 100px;
		    left: 0;
		}
		.all-image-one
		{
			width: 100%;
		}
		img.all-image-three
		{
			width: 100%;
		}
		.image_two
		{
			left: 0px;
			top: 30px;
		}
		.image_three
		{
			top: 0px;
    		position: unset;
		}
		.image_four
		{
			display: none;
		}
		.mob-im
		{
			position: relative;
		}
		.slider-mob.text
		{
			font-size: 15px;
		    font-weight: 900;
		    margin-bottom: 0px;
		}
		.shoes-image-mob
		{
			display: block;
			position: relative;
		    left: 23%;
    		margin-top: -31%;
		}
		.text-two
		{
			font-size: 15px;
		}
		.bold
		{
			font-size: 15px;
		}
		#lightboxwarranty, #sec-text
		{
			text-decoration: underline;
	   	text-decoration-color: cornflowerblue;
		}
		p.footer-text
		{
			margin: 0px 5%;
		}
		/*Tab*/
		/* .tab-2
		{
		    display: none;
		}
		.custom-tabs
		{
			padding-left: 0px;
    		padding-right: 0px;
		}
		 .tab-2
		{
			margin: 0px;
			position: absolute;
			width: 100%;
			z-index: 1;
			left: 0px;
			padding: 10px 0px;
			background: #e4e4e4;
			top: 40px;
			border-top: 1px solid gray;
		}
		 .tab-2 a
		{
		    width: 100%;
    		display: block;
		}
		 .tab-1
		{
			display: block;
		}
		 .tab-1 i 
		{
		  border: solid #3f3f3f;
		  border-width: 0 4px 4px 0;
		  display: inline-block;
		  padding: 6px;
		}
	 .tab-1 i.right 
		{
			position: absolute;
			top: 13%;
			transform: rotate(45deg);
			-webkit-transform: rotate(45deg);
			right: 20px;
		}*/
		i.arrow.right
        {
            border: solid #3f3f3f;
            border-width: 0 4px 4px 0;
            display: inline-block;
            padding: 6px;
            transform: rotate(45deg);
            /* -webkit-transform: rotate(45deg); */
            right: 30px;
            position: absolute;
            top: 10px;
        }
        
        .tab-2
        {
            display: none;
        }
        .tab-1
        {
        	 margin-right: 0px;
        }
        .tab-2
        {
            border-top: 1px solid gray;
            padding: 2%;
        }
         .tab-2
        {
            margin: 0px;
            position: absolute;
            width: 100%;
            z-index: 1;
            left: 0px;
            padding: 10px 0px;
            background: #e4e4e4;
            top: 40px;
            border-top: 1px solid gray;
        }
        .custom-tabs
        {
        	padding:10px;
        	position: relative;
        }
         .tab-2 a
        {
            width: 100%;
            display: block;
        }
	/*header*/
		.page-header
		{
			margin-bottom: 0px;
		}

		/*slider*/
	.owl-prev
	{
		/*position: absolute;
    	left: 10px;
    	bottom: 340px ! important;*/
    	
    	top: -400px;
	}
	.owl-next
	{
		/*position: absolute;
    	right: 10px;
        bottom: 340px;*/
        
        top: -400px;
	}
	.come-as-section .slider-image-section ul.list-slider.owl-loaded.owl-drag .owl-stage-outer
	{
		position: relative;
    	overflow: hidden;
	}
	.come-as-section .slider-image-section ul.list-slider.owl-loaded.owl-drag .owl-stage
	{
		position: relative;
	}
	.come-as-section .slider-image-section ul.list-slider.owl-loaded.owl-drag .owl-stage .owl-item
	{
		position: relative;
    	float: left;
	}
	.owl-carousel .owl-item img.slider-desk
	{
		display: none;
	}
	.owl-carousel .owl-item img.slider-mob
	{
		display: block;
	}
	.owl-carousel.owl-loaded
	{
		border-bottom: none;
	}
	}
	/*Tablet*/
@media screen and (min-width: 768px) and (max-width: 1024px) 
{
	img.classic-image
	{
		height: 120px;
	}
}	
</style>
