<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /*

<?php if ($block->getRealOrderId()) : ?><p><?= /* @escapeNotVerified * / __('Order #') . $block->getRealOrderId() ?></p><?php endif ?>
<?php if ($error = $block->getErrorMessage()) : ?><p><?= /* @escapeNotVerified * / $error ?></p><?php endif ?>
<p><?= /* @escapeNotVerified * / __('Click <a href="%1">here</a> to continue shopping.', $block->escapeUrl($block->getContinueShoppingUrl())) ?></p>

*/ ?>

<div class="page-title-wrapper-failure"><h1 class="page-title-failure">Sorry, your order <?php if ($block->getRealOrderId()) : ?><p><?= /* @escapeNotVerified */ __('(Order #') . $block->getRealOrderId() ?>)</p><?php endif ?> was not placed successfully.</div>
