<?php
/**
 * @copyright Copyright (c) 2016 www.tigren.com
 */
?>
<?php
/* @var \Magento\Catalog\Model\Product $_product */
$_product = $block->getProduct();
?>
<div class="mb-login-popup-title center">
    <strong><?php echo __('Added To Cart'); ?></strong>
</div>
<div class="mb-ajaxsuite-popup-border ajaxcart-success-box" id="sm-error">
    <div class="error-content">
        <p class="error-message">You need to choose size for your item / Selected size is not in our stock</p>
        <h2 class="product-name"><?php echo $_product->getName() ?></h2>
        <?php echo $block->getChildHtml('product_option'); ?>
        <?php echo $block->getChildHtml('product_image'); ?>
    </div>
  <!--   <div class="ajaxcart-buttons ajaxsuite-buttons">
        <button type="button" id="ajaxcart_cancel" class="action primary mb-ajaxsuite-close"
                title="<?php echo __('Continue Shopping') ?>">
            <span><?php echo __('Continue Shopping ') ?></span>
            <?php
            if ($popupTTL = $this->helper('Tigren\Ajaxsuite\Helper\Data')->getTTLAjaxSuite()) {
                ?>
                (<span class="ajaxsuite-autoclose-countdown"><?php echo $popupTTL ?></span>)
                <?php
            }
            ?>
        </button>
        <button type="button" id="ajaxcart_checkout" class="action focus primary"
                title="<?php echo __('View Cart') ?>"
                onClick="window.location = '<?php echo $block->getUrl('checkout/cart'); ?>'">
            <span><?php echo __('View Cart') ?></span>
        </button>
    </div> -->
</div>

<script>
    require([
        'jquery'
    ], function ($) {
        var productUrl = "<?= $_product->getProductUrl() ?>";
        var homepageUrl = "<?= $block->getUrl('') ?>";

        $('#mb-ajaxsuite-close').on('click', function (event) {
            event.preventDefault();
            window.location.href = productUrl;
            return false;
        });

        $('#ajaxcart_cancel').on('click', function (event) {
            event.preventDefault();
            window.location.href = homepageUrl;
            return false;
        });
    });
</script>